[tool.cibuildwheel]
build = "*"
skip = "pp*"
test-skip = ""

archs = ["auto", "aarch64"]

[tool.cibuildwheel.linux]
before-all = "yum -y update && yum install -y libffi-devel"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add libffi-dev"
